package rs.raf.demo.permiss;

public enum Permiss {

    CAN_CREATE_USER, CAN_READ_USER, CAN_UPDATE_USER, CAN_DELETE_USER,
    CAN_SEARCH_MACHINES, CAN_START_MACHINES, CAN_STOP_MACHINES, CAN_RESTART_MACHINES, CAN_CREATE_MACHINES,CAN_DESTROY_MACHINES

}
